# 数据库连接配置
spring:
  datasource:
    druid:
      url: jdbc:mysql://114.55.144.183:3307/ispace?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      initial-size: 1
      min-idle: 1
      max-active: 20
      test-on-borrow: true
      # MySQL 8.x: com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.jdbc.Driver
      # druid 状态监控
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: true
          slow-sql-millis: 2000
      # druid 监控过滤器
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      # druid 监控页面
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: 123456
        allow:

feign:
  hystrix:
    enabled: true

mybatis:
  type-aliases-package: com.ylon95.ispace.common.domain
  mapper-locations: classpath:mapper/*.xml
  configuration:
    cache-enabled: true