# 服务名
spring:
  application:
    name: ispace-upload
# 文件上传大小限制配置
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

# 服务端口
server:
  port: 8505

fastdfs:
  base:
    url: http://114.55.144.183:8888/
storage:
  type: fastdfs
  fastdfs:
    tracker_server: 114.55.144.183:22122