spring:
  application:
    name: ispace-config

  cloud:
    config:
      label: master
      uri: http://localhost:8888
      name: ispace-client-eureka
      profile: dev

      server:
        git:
          uri: https://github.com/Ylon95/ispace-config.git
          search-paths: respo
          username: Ylon95
          password: liang5294498H

server:
  port: 8888